[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "scaffold-auxilia"
dynamic = ["version"]
description = 'Auxiliary functions for working with scaffolds'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "0Huitzil", email = "frcastaneda@protonmail.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "cmlibs.maths >= 0.7.1",
  "cmlibs.utils >= 0.12.5",
  "cmlibs.zinc >= 4.2.1",
  "fieldfitter >= 0.6.0",
  "scaffoldfitter >= 0.11.1",
  "scaffoldmaker >= 0.12",
  "scipy",
  "numpy"
]

[project.urls]
Documentation = "https://github.com/0Huitzil/scaffold-auxilia#readme"
Issues = "https://github.com/0Huitzil/scaffold-auxilia/issues"
Source = "https://github.com/0Huitzil/scaffold-auxilia"

[tool.hatch.version]
path = "src/scaffold_auxilia/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/scaffold_auxilia tests}"

[tool.coverage.run]
source_pkgs = ["scaffold_auxilia", "tests"]
branch = true
parallel = true
omit = [
  "src/scaffold_auxilia/__about__.py",
]

[tool.coverage.paths]
scaffold_auxilia = ["src/scaffold_auxilia", "*/scaffold-auxilia/src/scaffold_auxilia"]
tests = ["tests", "*/scaffold-auxilia/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
